import {type Person,summary,dayResult,hours,escapeHtml as e,csvCell} from './audit';
export function saveFile(text:string,name:string,type:string){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);}
export function exportCsv(people:Person[],month:string,holidays:Record<string,string>,confirmed:boolean){
 const rows:unknown[][]=[['Colaborador','Arquivo','Data','Horas identificadas (decimais)','Horas esperadas','Resultado','Motivo','Ajuste de leitura','Confirmação OCR','Período confirmado']];
 for(const p of people)for(const d of p.days){const r=dayResult(p,d,month,holidays);rows.push([p.name,p.fileName,`${String(d.day).padStart(2,'0')}/${month.slice(5)}/${month.slice(0,4)}`,r.cents===null?'':hours(r.cents),hours(r.expected),r.status==='ok'?'OK':r.status==='review'?'Leitura a revisar':r.status==='excluded'?'Dispensado':'Divergência',r.reason,r.correction?.reason??'',p.ocr?(p.ocrReviewed?'Confirmado':'Revisão necessária'):'Texto do PDF',confirmed?'Sim':'Não']);}
 saveFile('\uFEFF'+rows.map(r=>r.map(csvCell).join(';')).join('\r\n'),`conferencia-${month}.csv`,'text/csv;charset=utf-8');
}
export function reportHtml(people:Person[],month:string,holidays:Record<string,string>,confirmed:boolean,notes:string[]=[]){
 const generated=new Date().toLocaleString('pt-BR');const pending=people.filter(p=>summary(p,month,holidays).status==='pending').length;const review=people.filter(p=>summary(p,month,holidays).status==='review').length;
 const head=`<!doctype html><html lang="pt-BR"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Conferência Dedicaciones · ${e(month)}</title><style>body{font:15px/1.5 'Segoe UI',Arial,sans-serif;color:#260717;max-width:1200px;margin:40px auto;padding:0 24px}h1{font-size:28px;font-weight:400;color:#480e2a;border-top:4px solid #ff0054;padding-top:20px}h2{margin-top:32px;font-size:20px;font-weight:400;color:#480e2a}table{width:100%;border-collapse:collapse;font-size:13px;margin:15px 0}td,th{border:1px solid #dedbd5;padding:8px;text-align:left}th{background:#f1f1ed}tr{break-inside:avoid}.notice{padding:15px;background:#fff3e2}.muted{color:#646459}.pending{color:#a44209}.review{color:#713450}.ok{color:#17684d}button{background:#480e2a;color:white;border:0;border-radius:6px;padding:10px 18px;cursor:pointer}@media print{@page{size:A4 landscape;margin:12mm}body{margin:0;padding:0}button{display:none}thead{display:table-header-group}}</style><button onclick="window.print()">Imprimir / salvar como PDF</button><h1>Conferência de horas · Dedicaciones</h1><p>Referência: <b>${e(month.slice(5)+'/'+month.slice(0,4))}</b> · Emitido em ${e(generated)}</p><p>${people.length} pessoas · ${pending} com divergências · ${review} com leitura a revisar.</p><p class="muted">Regra: soma de 8 horas por dia de segunda a sexta. Finais de semana e exceções registradas são dispensados. Valores em horas decimais. O estado de aprovação no Dedicaciones não altera esta conferência.</p>${!confirmed?'<p class="notice">PRELIMINAR: o mês de referência ainda não foi confirmado pelo responsável.</p>':''}${review?'<p class="notice">PRELIMINAR: existem leituras a revisar. Totais dessas pessoas podem estar incompletos.</p>':''}`;
 const table=`<h2>Resumo da equipe</h2><table><thead><tr><th>Colaborador</th><th>Horas identificadas</th><th>Horas esperadas</th><th>Dias de 8 h</th><th>Dias com divergência</th><th>Dias a revisar</th><th>Situação</th></tr></thead><tbody>${people.map(p=>{const s=summary(p,month,holidays);return `<tr><td>${e(p.name)}</td><td>${hours(s.total)} h</td><td>${hours(s.expected)} h</td><td>${s.ok}</td><td>${s.pending}</td><td>${s.review}</td><td class="${s.status}">${s.status==='ok'?'Sem divergências':s.status==='pending'?'Com divergências':'Leitura a revisar'}</td></tr>`}).join('')}</tbody></table>`;
 const detail=people.map(p=>`<h2>${e(p.name)}</h2><p class="muted">Arquivo: ${e(p.fileName)} · ${p.pageCount} páginas · ${p.ocr?(p.ocrReviewed?'Leitura de imagem confirmada pelo responsável':'Leitura de imagem não confirmada'):'Leitura de texto'} · Importado em ${e(new Date(p.importedAt).toLocaleString('pt-BR'))}</p>${p.warnings.map(w=>`<p class="notice">${e(w)}</p>`).join('')}<table><thead><tr><th>Dia</th><th>Horas</th><th>Esperado</th><th>Resultado / justificativa</th><th>Ajuste de leitura</th></tr></thead><tbody>${p.days.map(d=>{const r=dayResult(p,d,month,holidays);return `<tr><td>${String(d.day).padStart(2,'0')}/${month.slice(5)}</td><td>${r.cents===null?'Não lido':hours(r.cents)+' h'}</td><td>${hours(r.expected)} h</td><td class="${r.status}">${e(r.reason)}</td><td>${r.correction?e(`${d.cents===null?'Não lido':hours(d.cents)+' h'} → ${hours(r.correction.cents)} h. ${r.correction.reason}`):'—'}</td></tr>`}).join('')}</tbody></table>`).join('');
 return head+(notes.length?'<h2>Observações da importação</h2>'+notes.map(note=>'<p class=\"notice\">'+e(note)+'</p>').join(''):'')+table+detail+'<p class="muted">Conferência dos arquivos recebidos. Não comprova aprovação no sistema nem atualização posterior dos apontamentos.</p></html>';
}

