'use client';
import {assetPath} from '@/lib/asset-path';
import {useRef,useState} from 'react';
import {Clock3,Upload,ShieldCheck,Files,Download,ChevronRight,CheckCircle2,AlertTriangle,ScanText,CalendarDays,X,Plus,FileText,Save,FolderOpen} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from '@/components/ui/table';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription} from '@/components/ui/alert-dialog';
import {Checkbox} from '@/components/ui/checkbox';
import {Progress} from '@/components/ui/progress';
import {type Person,summary,dayResult,hours,toCents,monthDays,weekDay,validSession} from '@/lib/audit';
import {exportCsv,reportHtml,saveFile} from '@/lib/export';
const statusLabel=(s:string)=>s==='ok'?'Sem divergências':s==='pending'?'Com divergências':'Leitura a revisar';
const dayLabel=(s:string)=>s==='ok'?'8 h conferidas':s==='pending'?'Divergência':s==='review'?'Revisar leitura':'Dispensado';
function Status({value,day=false}:{value:string;day?:boolean}){return <span className={`badge ${value}`}>{value==='ok'?<CheckCircle2 size={13}/>:value==='pending'?<AlertTriangle size={13}/>:value==='review'?<ScanText size={13}/>:null}{day?dayLabel(value):statusLabel(value)}</span>}
function Choice({value,onChange,items,label}:{value:string;onChange:(s:string)=>void;items:{value:string;label:string}[];label:string}){return <Select value={value} onValueChange={v=>v!==null&&onChange(v)}><SelectTrigger className="min-w-40 h-10" aria-label={label}><SelectValue>{items.find(x=>x.value===value)?.label??value}</SelectValue></SelectTrigger><SelectContent>{items.map(x=><SelectItem key={x.value} value={x.value}>{x.label}</SelectItem>)}</SelectContent></Select>}
export default function Home(){
 const [month,setMonth]=useState('2026-08');const [people,setPeople]=useState<Person[]>([]);const [holidays,setHolidays]=useState<Record<string,string>>({});const [periodConfirmed,setConfirmed]=useState(false);
 const [busy,setBusy]=useState(false);const busyRef=useRef(false);const [progress,setProgress]=useState('');const [percent,setPercent]=useState(0);const [messages,setMessages]=useState<string[]>([]);const [dragging,setDragging]=useState(false);
 const [selected,setSelected]=useState<string|null>(null);const [selectedDay,setSelectedDay]=useState<number|null>(null);const [filter,setFilter]=useState('all');const [query,setQuery]=useState('');const [ruleOpen,setRuleOpen]=useState(false);const [resetOpen,setResetOpen]=useState(false);
 const [scope,setScope]=useState('all');const [from,setFrom]=useState('1');const [to,setTo]=useState('1');const [reason,setReason]=useState('');const [ruleError,setRuleError]=useState('');const [correction,setCorrection]=useState('');const [correctionReason,setCorrectionReason]=useState('');const [correctionError,setCorrectionError]=useState('');
 const fileRef=useRef<HTMLInputElement>(null),sessionRef=useRef<HTMLInputElement>(null);
 const p=people.find(p=>p.id===selected);const d=p?.days.find(d=>d.day===selectedDay);
 const stats=people.map(p=>summary(p,month,holidays));const total=stats.reduce((a,s)=>a+s.total,0);const complete=stats.filter(s=>s.status==='ok').length;const pendingDays=stats.reduce((a,s)=>a+s.pending,0);const reviewPeople=stats.filter(s=>s.status==='review').length;
 const filtered=people.filter(p=>p.name.toLocaleLowerCase().includes(query.toLocaleLowerCase())&&(filter==='all'||summary(p,month,holidays).status===filter));
 function update(id:string,fn:(p:Person)=>Person){setPeople(old=>old.map(p=>p.id===id?fn(p):p));}
 async function importFiles(files:File[]){
  if(busyRef.current||!/^20\d{2}-(0[1-9]|1[0-2])$/.test(month))return;
  busyRef.current=true;setBusy(true);setMessages([]);const errors:string[]=[];const accumulated=[...people];
  try{const {readPdf}=await import('@/lib/pdf-reader');for(let i=0;i<files.length;i++){
   const file=files[i];setPercent(Math.round(i/files.length*100));
   if(!/\.pdf$/i.test(file.name)){errors.push(`${file.name}: selecione um PDF.`);continue;}
   if(accumulated.length>=200){errors.push('Limite de 200 pessoas por conferência.');break;}
   try{const record=await readPdf(file,month,setProgress);if(accumulated.some(p=>p.hash===record.hash)){errors.push(`${file.name}: conteúdo já importado; duplicata ignorada.`);continue;}
    if(accumulated.some(p=>p.name.trim().toLowerCase()===record.name.trim().toLowerCase())){errors.push(`${file.name}: já existe uma pessoa com esse nome. Remova a versão anterior nos detalhes antes de substituir.`);continue;}
    accumulated.push(record);setPeople([...accumulated]);
   }catch(e){errors.push(`${file.name}: ${e instanceof Error?e.message:'Não foi possível ler o PDF.'}`);}
  }}catch{errors.push('Não foi possível iniciar a leitura. Recarregue a aplicação e tente novamente.');}finally{setMessages(errors);setProgress('');setPercent(100);setBusy(false);busyRef.current=false;if(fileRef.current)fileRef.current.value='';}
 }
 async function restore(file:File){if(people.length){setMessages(['Inicie uma nova conferência antes de abrir uma sessão salva.']);return;}try{if(file.size>20*1024*1024)throw new Error('Arquivo de sessão acima de 20 MB.');const data=JSON.parse(await file.text());if(!validSession(data))throw new Error('Sessão inválida ou de uma versão incompatível.');setMonth(data.month);setPeople(data.people);setHolidays(data.holidays);setConfirmed(data.periodConfirmed);setMessages(['Sessão restaurada. Os PDFs originais não são incluídos na sessão salva.']);}catch(e){setMessages([e instanceof Error?e.message:'Não foi possível abrir a sessão.']);}finally{if(sessionRef.current)sessionRef.current.value='';}}
 function saveSession(){saveFile(JSON.stringify({version:1,month,people,holidays,periodConfirmed},null,2),`conferencia-${month}.json`,'application/json');}
 function addException(){const start=Number(from),end=Number(to);if(!Number.isInteger(start)||!Number.isInteger(end)||start<1||end<start||end>monthDays(month)||!reason.trim()){setRuleError('Informe um intervalo válido e a justificativa.');return;}const days=Object.fromEntries(Array.from({length:end-start+1},(_,i)=>[start+i,reason.trim()]));if(scope==='all')setHolidays(h=>({...h,...days}));else update(scope,p=>({...p,exceptions:{...p.exceptions,...days}}));setRuleOpen(false);setReason('');setRuleError('');}
 function correctDay(){if(!p||!d)return;const cents=toCents(correction);if(cents===null||!correctionReason.trim()){setCorrectionError('Informe de 0 a 24 horas decimais e explique o ajuste de leitura.');return;}update(p.id,p=>({...p,corrections:{...p.corrections,[d.day]:{cents,reason:correctionReason.trim()}}}));setSelectedDay(null);}
 function openDay(person:Person,day:number){setSelected(person.id);setSelectedDay(day);const d=person.days.find(x=>x.day===day)!;setCorrection(person.corrections[day]?hours(person.corrections[day].cents):d.cents===null?'':hours(d.cents));setCorrectionReason('');setCorrectionError('');}
 const reference=month?new Date(Number(month.slice(0,4)),Number(month.slice(5))-1,1).toLocaleDateString('pt-BR',{month:'long',year:'numeric'}):'Selecione o mês';
 return <><header className="topbar no-print"><div className="brand"><img className="brand-logo" src={assetPath('/brand/minsait-logo-dark.svg')} alt="Minsait" width={185} height={20}/><span className="brand-context">Conferência de horas</span></div><span className="subtle">Dedicaciones · Fechamento mensal</span></header><main>
 <div className="no-print"><div className="heading"><div><p className="eyebrow">Dedicaciones · Fechamento mensal</p><h1>Conferência de horas.</h1><p className="subtle">Confira a jornada de 8 horas a partir dos PDFs do Dedicaciones.</p></div><div className="actions"><Button variant="outline" className="btn" onClick={()=>sessionRef.current?.click()} disabled={busy}><FolderOpen/>Abrir sessão</Button><Button variant="outline" className="btn" onClick={saveSession} disabled={!people.length||busy}><Save/>Salvar sessão</Button></div></div>
 <input ref={sessionRef} type="file" accept=".json" hidden onChange={e=>e.target.files?.[0]&&restore(e.target.files[0])}/>
 <section className="panel"><div className="toolbar"><div className="actions"><label className="field">Mês de referência<input type="month" value={month} min="2000-01" max="2099-12" disabled={people.length>0||busy} onChange={e=>{setMonth(e.target.value);setConfirmed(false);}}/></label><div className="field"><span>Regra da conferência</span><div className="actions" style={{height:40}}><Clock3 size={17}/><span>8 h · segunda a sexta</span></div></div></div><div className="actions"><Button variant="outline" className="btn" onClick={()=>{setScope('all');setRuleOpen(true)}} disabled={busy||!month}><CalendarDays/>Feriados e exceções</Button>{people.length>0&&<Button variant="ghost" className="btn" disabled={busy} onClick={()=>setResetOpen(true)}>Nova conferência</Button>}</div></div>
 <div className={`dropzone ${dragging?'dragging':''}`} onDragOver={e=>{e.preventDefault();setDragging(true)}} onDragLeave={()=>setDragging(false)} onDrop={e=>{e.preventDefault();setDragging(false);void importFiles(Array.from(e.dataTransfer.files))}}><Upload size={28} color="#ff0054"/><div style={{flex:1}}><h3>Importar PDFs da equipe</h3><p className="subtle">Arraste os arquivos ou selecione vários de uma vez. O nome do arquivo identifica a pessoa.</p></div><Button className="btn" onClick={()=>fileRef.current?.click()} disabled={busy||!month}><Plus/>Selecionar PDFs</Button><input ref={fileRef} type="file" accept=".pdf,application/pdf" multiple hidden onChange={e=>void importFiles(Array.from(e.target.files??[]))}/></div>
 {busy&&<div className="progressline" role="status"><p>{progress||'Preparando leitura…'}</p><Progress value={percent} className="mt-2"/><p className="subtle mt-1">PDFs em imagem podem levar mais tempo. Mantenha esta página aberta.</p></div>}
 <div style={{padding:'0 24px 20px'}}><label className="checkline"><Checkbox checked={periodConfirmed} onCheckedChange={v=>setConfirmed(Boolean(v))} disabled={busy||!month}/><span>Confirmo que os PDFs correspondem a <strong>{reference}</strong>.</span></label><p className="subtle" style={{marginTop:6}}>A data de impressão não identifica o mês dos apontamentos. Feriados não são aplicados automaticamente.</p></div></section>
 {messages.length>0&&<div className="notice" role="status">{messages.map((m,i)=><p key={i}>{m}</p>)}</div>}
 <div className="stats"><div className="stat"><span className="label">Pessoas importadas</span><strong>{people.length||'—'}</strong><span className="subtle">{people.length?'Arquivos recebidos':'Aguardando os PDFs'}</span></div><div className="stat"><span className="label">Sem divergências</span><strong className="good">{people.length?complete:'—'}</strong><span className="subtle">{people.length?`de ${people.length} pessoas`:'Todos os dias conferidos'}</span></div><div className="stat"><span className="label">Dias com divergência</span><strong className="warn">{people.length?pendingDays:'—'}</strong><span className="subtle">{reviewPeople?`${reviewPeople} pessoa(s) também com leitura a revisar`:'Abaixo ou acima de 8 horas'}</span></div><div className="stat"><span className="label">Horas identificadas</span><strong>{people.length?hours(total):'—'}{people.length>0&&<span style={{fontSize:18}}> h</span>}</strong><span className="subtle">{reviewPeople?'Total provisório: há leituras a revisar':'Soma dos lançamentos'}</span></div></div>
 {people.length>0&&(!periodConfirmed||reviewPeople>0)&&<p className="notice"><strong>Conferência preliminar.</strong> {!periodConfirmed?'Confirme o mês de referência. ':''}{reviewPeople>0?'Revise as leituras sinalizadas antes de concluir o fechamento.':''}</p>}
 <section className="panel"><div className="section-head"><div><h2>Resumo da equipe</h2><p className="subtle">{reference} · {Array.from({length:month?monthDays(month):0},(_,i)=>i+1).filter(d=>![0,6].includes(weekDay(month,d))).length} dias de segunda a sexta</p></div><div className="actions"><Button variant="outline" className="btn" disabled={!people.length||busy} onClick={()=>exportCsv(people,month,holidays,periodConfirmed)}><Download/>CSV detalhado</Button><Button className="btn" disabled={!people.length||busy} onClick={()=>saveFile(reportHtml(people,month,holidays,periodConfirmed,messages),`relatorio-dedicaciones-${month}.html`,'text/html;charset=utf-8')}><FileText/>Relatório para gestão</Button></div></div>
 {!people.length?<div className="empty"><Files size={34} color="#866370"/><h3>Os apontamentos da equipe aparecerão aqui</h3><p className="subtle">Cada dia será conferido individualmente, somando os lançamentos entre projetos.</p></div>:<>
 <div className="toolbar"><label className="field"><span className="sr-only">Buscar colaborador</span><input placeholder="Buscar colaborador…" value={query} onChange={e=>setQuery(e.target.value)}/></label><Choice label="Filtrar situação" value={filter} onChange={setFilter} items={[{value:'all',label:'Todas as situações'},{value:'pending',label:'Com divergências'},{value:'review',label:'Leitura a revisar'},{value:'ok',label:'Sem divergências'}]}/></div>
 <Tabs defaultValue="summary"><TabsList variant="line" className="mx-6 mb-3"><TabsTrigger value="summary">Por colaborador</TabsTrigger><TabsTrigger value="calendar">Mapa diário</TabsTrigger></TabsList><TabsContent value="summary"><Table><TableHeader><TableRow><TableHead className="pl-6">Colaborador</TableHead><TableHead>Horas</TableHead><TableHead>Esperado</TableHead><TableHead>Dias de 8 h</TableHead><TableHead>Divergências</TableHead><TableHead>Situação</TableHead><TableHead><span className="sr-only">Detalhes</span></TableHead></TableRow></TableHeader><TableBody>{filtered.map(person=>{const s=summary(person,month,holidays);return <TableRow key={person.id}><TableCell className="pl-6 py-4"><div className="person"><span className="avatar">{person.name.slice(0,2).toUpperCase()}</span><div><button className="rowbtn" onClick={()=>{setSelectedDay(null);setSelected(person.id)}}>{person.name}</button><p className="subtle">{person.ocr?'PDF em imagem':'PDF com texto'} · {person.pageCount} páginas</p></div></div></TableCell><TableCell className="numeric">{hours(s.total)} h{s.review>0?' *':''}</TableCell><TableCell className="numeric">{hours(s.expected)} h</TableCell><TableCell className="numeric">{s.ok}</TableCell><TableCell>{s.pending?`${s.pending} dia(s)`:'—'}{s.review>0&&<p className="subtle">{s.review} a revisar</p>}</TableCell><TableCell><Status value={s.status}/></TableCell><TableCell><Button variant="ghost" size="icon" aria-label={`Ver detalhes de ${person.name}`} onClick={()=>{setSelectedDay(null);setSelected(person.id)}}><ChevronRight size={18}/></Button></TableCell></TableRow>})}</TableBody></Table></TabsContent><TabsContent value="calendar"><div className="table-wrap"><Table><TableHeader><TableRow><TableHead className="pl-6 min-w-40">Colaborador</TableHead>{Array.from({length:monthDays(month)},(_,i)=>i+1).map(day=><TableHead key={day} className="daycell">{String(day).padStart(2,'0')}<div className="calendarlabel">{['D','S','T','Q','Q','S','S'][weekDay(month,day)]}</div></TableHead>)}</TableRow></TableHeader><TableBody>{filtered.map(person=><TableRow key={person.id}><TableCell className="pl-6"><button className="rowbtn" onClick={()=>{setSelectedDay(null);setSelected(person.id)}}>{person.name}</button></TableCell>{person.days.map(d=>{const r=dayResult(person,d,month,holidays);return <TableCell className="daycell" key={d.day}><button className={`daybutton ${r.status}`} onClick={()=>openDay(person,d.day)} aria-label={`${person.name}, dia ${d.day}: ${r.cents===null?'não lido':hours(r.cents)+' horas'}, ${r.reason}`} title={`${r.reason}${r.cents!==null?' · '+hours(r.cents)+' h':''}`}>{r.cents===null?'?':r.status==='excluded'&&r.cents===0?'—':hours(r.cents)}</button></TableCell>})}</TableRow>)}</TableBody></Table></div></TabsContent></Tabs>
 {!filtered.length&&<p className="empty">Nenhuma pessoa encontrada para este filtro.</p>}<div className="toolbar"><div className="legend"><span><i className="dot" style={{background:'#258458'}}/>8 h conferidas</span><span><i className="dot" style={{background:'#c37224'}}/>Divergência</span><span><i className="dot" style={{background:'#866370'}}/>Leitura a revisar</span><span><i className="dot" style={{background:'#aaaa9f'}}/>Dispensado</span></div><span className="subtle">Horas decimais · clique para ver os dias</span></div></>}
 </section>
 {Object.keys(holidays).length>0&&<section className="panel mt-5 p-5"><h3>Exceções para toda a equipe</h3><div className="actions mt-3">{Object.entries(holidays).map(([day,note])=><span key={day} className="badge excluded">Dia {day}: {note}<button aria-label={`Remover exceção do dia ${day}`} onClick={()=>setHolidays(h=>{const n={...h};delete n[day];return n})}><X size={14}/></button></span>)}</div></section>}
 <p className="footnote"><ShieldCheck size={17} className="shrink-0"/><span>Os PDFs são processados neste navegador. Os dados ficam nesta sessão até você fechar ou recarregar a página; use “Salvar sessão” para continuar depois. O relatório contém os dados da equipe e pode ser compartilhado como arquivo. Esta conferência não altera o Dedicaciones.</span></p></div>
 </main>
 <Sheet open={!!p} onOpenChange={open=>{if(!open){setSelected(null);setSelectedDay(null)}}}><SheetContent className="sheetwide"><SheetHeader className="p-6"><SheetTitle className="text-2xl">{p?.name}</SheetTitle><SheetDescription>{p?.fileName} · {reference}</SheetDescription></SheetHeader>{p&&<div className="detailbody"><label className="field mb-4">Nome do colaborador<input value={p.name} onChange={e=>update(p.id,p=>({...p,name:e.target.value}))}/></label><div className="actions mb-4"><Status value={summary(p,month,holidays).status}/><span>{hours(summary(p,month,holidays).total)} h identificadas</span><Button variant="outline" className="btn" onClick={()=>{setScope(p.id);setRuleOpen(true)}}><Plus/>Exceção</Button></div>{p.warnings.map((w,i)=><p className="notice" key={i}>{w}</p>)}{p.ocr&&<div className="notice"><p>Este PDF foi lido por reconhecimento de imagem. Compare os valores com o original antes de confirmar.</p><label className="checkline mt-3"><Checkbox checked={p.ocrReviewed} onCheckedChange={v=>update(p.id,p=>({...p,ocrReviewed:Boolean(v)}))}/>Conferi todos os valores com o PDF original.</label></div>}
 <p className="subtle mb-3">Selecione um dia para ver a leitura original ou registrar um ajuste.</p>{p.days.map(day=>{const r=dayResult(p,day,month,holidays);return <div key={day.day}><div className="detail-row"><button className="rowbtn" onClick={()=>openDay(p,day.day)}>{String(day.day).padStart(2,'0')}/{month.slice(5)}</button><span className="numeric">{r.cents===null?'Não lido':hours(r.cents)+' h'}</span><div><Status value={r.status} day/>{r.exception&&<p className="subtle">{r.exception}</p>}{r.correction&&<p className="subtle">Leitura ajustada</p>}</div><button aria-label={`Detalhes do dia ${day.day}`} onClick={()=>openDay(p,day.day)}><ChevronRight size={18}/></button></div>{selectedDay===day.day&&<div className="rulebox my-3"><h3>Dia {day.day} · evidência da leitura</h3><p className="subtle">{day.entries.length?`Lançamentos identificados: ${day.entries.map(x=>hours(x)+' h').join(' + ')}`:'Nenhum lançamento reconhecido.'}</p><pre className="evidence">{day.evidence}</pre>{p.exceptions[day.day]&&<Button variant="outline" className="btn mb-3" onClick={()=>update(p.id,p=>{const exceptions={...p.exceptions};delete exceptions[day.day];return {...p,exceptions}})}>Remover exceção individual</Button>}<div className="detailgrid"><label className="field">Horas corretas no PDF<input value={correction} inputMode="decimal" placeholder="Ex.: 8 ou 7,5" onChange={e=>setCorrection(e.target.value)}/></label><label className="field">Motivo do ajuste de leitura<input value={correctionReason} onChange={e=>setCorrectionReason(e.target.value)} placeholder="Conferido no PDF original" maxLength={500}/></label></div><p className="subtle mt-2">Ajuste apenas erros de leitura. Para férias ou ausências, registre uma exceção.</p>{correctionError&&<p className="bad mt-2" role="alert">{correctionError}</p>}<div className="actions mt-3"><Button className="btn" onClick={correctDay}>Salvar ajuste</Button>{r.correction&&<Button variant="outline" className="btn" onClick={()=>update(p.id,p=>{const corrections={...p.corrections};delete corrections[day.day];return {...p,corrections}})}>Restaurar leitura original</Button>}<Button variant="ghost" className="btn" onClick={()=>setSelectedDay(null)}>Fechar dia</Button></div></div>}</div>})}<Button variant="outline" className="btn mt-6" onClick={()=>{setPeople(old=>old.filter(x=>x.id!==p.id));setSelected(null)}} disabled={busy}>Remover este arquivo da conferência</Button></div>}</SheetContent></Sheet>
 <Dialog open={ruleOpen} onOpenChange={setRuleOpen}><DialogContent className="sm:max-w-lg p-6"><DialogHeader><DialogTitle>Feriado ou exceção de jornada</DialogTitle><DialogDescription>O intervalo ficará dispensado da regra de 8 horas. A justificativa será incluída no relatório.</DialogDescription></DialogHeader><div className="modalform"><label className="field">Aplicar a<Choice label="Pessoa ou equipe" value={scope} onChange={setScope} items={[{value:'all',label:'Toda a equipe'},...people.map(p=>({value:p.id,label:p.name}))]}/></label><div className="detailgrid"><label className="field">Do dia<input type="number" min="1" max={month?monthDays(month):31} value={from} onChange={e=>setFrom(e.target.value)}/></label><label className="field">Até o dia<input type="number" min="1" max={month?monthDays(month):31} value={to} onChange={e=>setTo(e.target.value)}/></label></div><label className="field">Justificativa<input value={reason} onChange={e=>setReason(e.target.value)} placeholder="Ex.: férias, feriado municipal ou ausência" maxLength={500}/></label>{ruleError&&<p className="bad" role="alert">{ruleError}</p>}<Button className="btn" onClick={addException}>Registrar exceção</Button></div></DialogContent></Dialog>
 <AlertDialog open={resetOpen} onOpenChange={setResetOpen}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Iniciar nova conferência?</AlertDialogTitle><AlertDialogDescription>Os dados desta sessão serão removidos da tela. Salve a sessão se precisar retomá-la depois.</AlertDialogDescription></AlertDialogHeader><div className="actions"><Button variant="ghost" className="btn" onClick={()=>setResetOpen(false)}>Cancelar</Button><Button variant="outline" className="btn" onClick={()=>{saveSession();setResetOpen(false)}}>Salvar sessão atual</Button><Button className="btn" onClick={()=>{setPeople([]);setHolidays({});setConfirmed(false);setMessages([]);setQuery('');setFilter('all');setResetOpen(false);setSelected(null)}}>Iniciar nova</Button></div></AlertDialogContent></AlertDialog>
 </>;
}

